# Лабораторная работа №2

#### Импорт ввсех необходимых модулей

In [4]:
#! /usr/bin/env pthon3
# -*- coding: utf-8 -*-

In [5]:
from ipywidgets import interact
from ipywidgets import widgets 
from IPython.display import display
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import axes
from matplotlib import rcParams, rc
from random import uniform

In [22]:
def get_equation(initial_x, initial_y):
    assert(len(initial_x) == 5)
    assert(len(initial_y) == 5)
    second_order_equation_x_y = lambda x,y: [x**2, x*y, y**2, 2*x, 2*y]

    coefficients = np.array(
        [second_order_equation_x_y(x, y) for x, y in zip(initial_x, initial_y)]
    )
    
    print(coefficients)
    
    b = np.array([-1.] * 5)
    
    x = np.linalg.solve(coefficients, b)
    
    return x
    

print(
    get_equation(
        [0., 0., -1., -2., -1.], 
        [0., 2.,  0.,  1.,  3.]
    )
)
    
    

[[ 0.  0.  0.  0.  0.]
 [ 4.  4.  4.  4.  4.]
 [ 1. -0.  0. -2.  0.]
 [ 4. -2.  1. -4.  2.]
 [ 1. -3.  9. -2.  6.]]


LinAlgError: Singular matrix